
class InitDataBaseData {

  //#region Create Json Rows: Users [Data for Debug]
  static String createJsonRowsForUsers() {

    String userRowsJson =
        '['
        '{'
        '"userId": "1", '
        '"personCardId": "", '
        '"email": "shr.harari@gmail.com", '
        '"firstName": "שחר", '
        '"lastName": "הררי", '
        '"password": "qqqq", '
        '"userType": "SystemAdmin", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"userId": "2", '
        '"personCardId": "", '
        '"email": "alec.baldwin@gmail.com", '
        '"firstName": "אלק", '
        '"lastName": "באלדווין", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"userId": "3", '
        '"personCardId": "", '
        '"email": "gal_gadot@gmail.com", '
        '"firstName": "גל", '
        '"lastName": "גדות", '
        '"password": "qqqq", '
        '"userType": "SystemAdmin", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"userId": "4", '
        '"personCardId": "", '
        '"email": "tom_cruise@gmail.com", '
        '"firstName": "טום", '
        '"lastName": "קרוז", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"userId": "5", '
        '"personCardId": "", '
        '"email": "cameron_diaz@gmail.com", '
        '"firstName": "קמרון", '
        '"lastName": "דיאז", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"userId": "6", '
        '"personCardId": "", '
        '"email": "harrison_ford@gmail.com", '
        '"firstName": "האריסון", '
        '"lastName": "פורד", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"userId": "7", '
        '"personCardId": "", '
        '"email": "jack_nicholson@gmail.com", '
        '"firstName": "גק", '
        '"lastName": "ניקולסון", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"userId": "8", '
        '"personCardId": "", '
        '"email": "julia_roberts@gmail.com", '
        '"firstName": "גוליה", '
        '"lastName": "רוברטס", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"userId": "9", '
        '"personCardId": "", '
        '"email": "paul_newman@gmail.com", '
        '"firstName": "פול", '
        '"lastName": "ניומן", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"userId": "10", '
        '"personCardId": "", '
        '"email": "robert_de_niro@gmail.com", '
        '"firstName": "רוברט", '
        '"lastName": "דה-נירו", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"userId": "11", '
        '"personCardId": "", '
        '"email": "uma_thurman@gmail.com", '
        '"firstName": "אומה", '
        '"lastName": "תורמן", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"userId": "12", '
        '"personCardId": "", '
        '"email": "dustin_hoffman@gmail.com", '
        '"firstName": "דאסטין", '
        '"lastName": "הופמן", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"userId": "20", '
        '"personCardId": "", '
        '"email": "roie_shaposhnik@gmail.com", '
        '"firstName": "רועי", '
        '"lastName": "שפושניק", '
        '"password": "qqqq", '
        '"userType": "Guest", '
        '"stayConnected": 1 '
        '}'
        ']';

    return userRowsJson;
  }
  //#endregion

  //#region Create Json Rows: PersonCards [Data for Debug]
  static String createJsonRowsForPersonCards() {
    final String someText = "\\nשל כרטיס הביקור של אלק באלדווי\\nפירוט נוסף\\nועוד פירוט\\nשורה נונספת ארוכה מאודדדדדדדדדדד דדדדדדדדדדדדד דדדדדדדדדדדד  דדדדד\\nועוד שורה ארררררוככככה יחדגיכחגי דגיכגדי דגכי ידגכי דגכי דגכי דגכי\\nסוף";

    String personCardRowsJson =
    '['
      '{'
        '"personCardId": "1", '
        '"email": "shr.harari@gmail.com", '
        '"firstName": "שחר", '
        '"lastName": "הררי", '
        '"firstNameEng": "Shahar", '
        '"lastNameEng": "Harari", '
        '"phoneNumber": "+972525464640", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "525464640", '
        '"phoneNumberCleanLongFormat": "972525464640", '
        '"pictureUrl": "", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של שחר הררי", '
        '"internetSiteUrl": "https://www.google.co.il/", '
        '"address": "הנשיאים 6, הוד-השרון ישראל", '
        '"areaId": "ישראל", '
        '"clusterId": "גוש דן", '
        '"clubId": "תל-אביב", '
        '"roleId": "1" '
      '},'
      '{'
        '"personCardId": "2", '
        '"email": "alec.baldwin@gmail.com", '
        '"firstName": "אלק", '
        '"lastName": "באלדווין", '
        '"firstNameEng": "Alec", '
        '"lastNameEng": "Baldwin", '
        '"phoneNumber": "+972521111111", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "521111111", '
        '"phoneNumberCleanLongFormat": "972521111111", '
        '"pictureUrl": "", '
        '"cardDescription": "$someText", '
        '"internetSiteUrl": "", '
        '"address": "ויצמן 32, כפר-סבא ישראל", '
        '"areaId": "ישראל", '
        '"clusterId": "גוש דן", '
        '"clubId": "תל-אביב", '
        '"roleId": "6" '
      '},'
      '{'
        '"personCardId": "3", '
        '"email": "gal_gadot@gmail.com", '
        '"firstName": "גל", '
        '"lastName": "גדות", '
        '"firstNameEng": "Gal", '
        '"lastNameEng": "Gadot", '
        '"phoneNumber": "+972522222222", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "522222222", '
        '"phoneNumberCleanLongFormat": "972522222222", '
        '"pictureUrl": "", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של גל גדות", '
        '"internetSiteUrl": "", '
        '"address": "יפו 32 ירושלים ישראל", '
        '"areaId": "ישראל", '
        '"clusterId": "שומרון", '
        '"clubId": "קיסריה", '
        '"roleId": "3" '
      '},'
      '{'
        '"personCardId": "4", '
        '"email": "tom_cruise@gmail.com", '
        '"firstName": "טום", '
        '"lastName": "קרוז", '
        '"firstNameEng": "Tom", '
        '"lastNameEng": "Cruise", '
        '"phoneNumber": "+972523333333", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "523333333", '
        '"phoneNumberCleanLongFormat": "972523333333", '
        '"pictureUrl": "", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של טום קרוז", '
        '"internetSiteUrl": "", '
        '"address": "הכנסת 1, ירושלים", '
        '"areaId": "ישראל", '
        '"clusterId": "שומרון", '
        '"clubId": "קיסריה", '
        '"roleId": "4" '
      '},'
      '{'
        '"personCardId": "5", '
        '"email": "cameron_diaz@gmail.com", '
        '"firstName": "קמרון", '
        '"lastName": "דיאז", '
        '"firstNameEng": "Cameron", '
        '"lastNameEng": "Diaz", '
        '"phoneNumber": "+972524444444", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "524444444", '
        '"phoneNumberCleanLongFormat": "972524444444", '
        '"pictureUrl": "", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של קמרון דיאז", '
        '"internetSiteUrl": "", '
        '"address": "תל-חי 18, כפר-סבא ישראל", '
        '"areaId": "ישראל", '
        '"clusterId": "שומרון", '
        '"clubId": "קיסריה", '
        '"roleId": "5" '
      '},'
      '{'
        '"personCardId": "6", '
        '"email": "harrison_ford@gmail.com", '
        '"firstName": "האריסון", '
        '"lastName": "פורד", '
        '"firstNameEng": "Harrison", '
        '"lastNameEng": "Ford", '
        '"phoneNumber": "+972525555555", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "525555555", '
        '"phoneNumberCleanLongFormat": "972525555555", '
        '"pictureUrl": "", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של האריסון פורד", '
        '"internetSiteUrl": "", '
        '"address": "סוקולוב 6, נתניה", '
        '"areaId": "ישראל", '
        '"clusterId": "שומרון", '
        '"clubId": "קיסריה", '
        '"roleId": "6" '
      '},'
      '{'
        '"personCardId": "7", '
        '"email": "jack_nicholson@gmail.com", '
        '"firstName": "גק", '
        '"lastName": "ניקולסון", '
        '"firstNameEng": "Jack", '
        '"lastNameEng": "Nicholson", '
        '"phoneNumber": "+972526666666", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "526666666", '
        '"phoneNumberCleanLongFormat": "9726666666", '
        '"pictureUrl": "", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של גק ניקולסון", '
        '"internetSiteUrl": "", '
        '"address": "ויצמן 6, חדרה", '
        '"areaId": "ישראל", '
        '"clusterId": "שומרון", '
        '"clubId": "כפר יונה", '
        '"roleId": "6" '
      '},'
      '{'
        '"personCardId": "8", '
        '"email": "julia_roberts@gmail.com", '
        '"firstName": "גוליה", '
        '"lastName": "רוברטס", '
        '"firstNameEng": "Julia", '
        '"lastNameEng": "Roberts", '
        '"phoneNumber": "+972527777777", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "527777777", '
        '"phoneNumberCleanLongFormat": "97257777777", '
        '"pictureUrl": "", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של גוליה רוברטס", '
        '"internetSiteUrl": "google.com", '
        '"address": "סוקולוב 6, רמת-השרון", '
        '"areaId": "ישראל", '
        '"clusterId": "חיפה והקריות", '
        '"clubId": "חיפה", '
        '"roleId": "4" '
      '},'
      '{'
        '"personCardId": "9", '
        '"email": "paul_newman@gmail.com", '
        '"firstName": "פול", '
        '"lastName": "ניומן", '
        '"firstNameEng": "Paul", '
        '"lastNameEng": "Newman", '
        '"phoneNumber": "+972528888888", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "528888888", '
        '"phoneNumberCleanLongFormat": "97258888888", '
        '"pictureUrl": "", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של פול ניומן", '
        '"internetSiteUrl": "google.com", '
        '"address": "וינגייט 56, באר-שבע", '
        '"areaId": "ישראל", '
        '"clusterId": "חיפה והקריות", '
        '"clubId": "חיפה", '
        '"roleId": "6" '
      '},'
      '{'
        '"personCardId": "10", '
        '"email": "robert_de_niro@gmail.com", '
        '"firstName": "רוברט", '
        '"lastName": "דה-נירו", '
        '"firstNameEng": "Robert", '
        '"lastNameEng": "De_niro", '
        '"phoneNumber": "+972529999999", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "529999999", '
        '"phoneNumberCleanLongFormat": "97259999999", '
        '"pictureUrl": "", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של רוברט דה-נירו", '
        '"internetSiteUrl": "google.com", '
        '"address": "הנשיא 6, פתח-תקווה", '
        '"areaId": "ארצות הברית", '
        '"clusterId": "חוף מערבי", '
        '"clubId": "ניו-יורק", '
        '"roleId": "3" '
      '},'
      '{'
        '"personCardId": "11", '
        '"email": "uma_thurman@gmail.com", '
        '"firstName": "אומה", '
        '"lastName": "תורמן", '
        '"firstNameEng": "Uma", '
        '"lastNameEng": "Thurman", '
        '"phoneNumber": "+972529999999", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "529999999", '
        '"phoneNumberCleanLongFormat": "97259999999", '
        '"pictureUrl": "", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של אומה תורמן", '
        '"internetSiteUrl": "google.com", '
        '"address": "6767 Hollywood Blvd, Los Angeles, CA 90028, ארצות הברית", '
        '"areaId": "צרפת", '
        '"clusterId": "מרכז צרפת", '
        '"clubId": "פריז", '
        '"roleId": "3" '
      '},'
      '{'
        '"personCardId": "12", '
        '"email": "dustin_hoffman@gmail.com", '
        '"firstName": "דאסטין", '
        '"lastName": "הופמן", '
        '"firstNameEng": "Dustin", '
        '"lastNameEng": "Hoffman", '
        '"phoneNumber": "+972521212121", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "521212121", '
        '"phoneNumberCleanLongFormat": "972521212121", '
        '"pictureUrl": "", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של דאסטין הופמן", '
        '"internetSiteUrl": "google.com", '
        '"address": "הירקון 7, תל-אביב", '
        '"areaId": "ישראל", '
        '"clusterId": "חיפה והקריות", '
        '"clubId": "נהריה", '
        '"roleId": "6" '
      '}'
    ']';

    return personCardRowsJson;
  }
  //#endregion

  //#region Create Json Rows: Events [Data for Debug]
  static String createJsonRowsForEvents() {

    String eventsListJson =
      '['
      '{'
        '"eventId": "1", '
        '"eventName": "מסיבת סיום גדולה", '
        '"eventPictureUrl": "", '
        '"eventDescription": "מסיבת סיום גדולה בעיר", '
        '"eventStartDateTime": "${DateTime.now().toString()}", '
        '"eventEndDateTime": "${DateTime.now().add(Duration(hours: 1)).toString()}", '
        '"eventLocation": "ויצמן 32, כפר-סבא ישראל", '
        '"eventManager": "shr.harari@gmail.com" '
      '},'
      '{'
        '"eventId": "2", '
        '"eventName": "מסיבת סיום", '
        '"eventPictureUrl": "", '
        '"eventDescription": "מסיבת סיום גדולה בעיר", '
        '"eventStartDateTime": "2020-07-25 09:30:00.000", '
        '"eventEndDateTime": "2020-07-25 10:30:00.000", '
        '"eventLocation": "6767 Hollywood Blvd, Los Angeles, CA 90028, ארצות הברית", '
        '"eventManager": "shr.harari@gmail.com" '
      '},'
      '{'
        '"eventId": "3", '
        '"eventName": "הנואם הצעיר אירוע בוקר", '
        '"eventPictureUrl": "", '
        '"eventDescription": "הנואם הצעיר - מחוז מרכז", '
        '"eventStartDateTime": "2020-08-12 08:00:00.000", '
        '"eventEndDateTime": "2020-08-12 10:00:00.000", '
        '"eventLocation": "יפו 32 ירושלים ישראל", '
        '"eventManager": "shr.harari@gmail.com" '
      '},'
      '{'
        '"eventId": "4", '
        '"eventName": "הנואם הצעיר אירוע ערב", '
        '"eventPictureUrl": "", '
        '"eventDescription": "תחרות ארצית - הנואם הצעיר", '
        '"eventStartDateTime": "2020-09-18 20:00:00.000", '
        '"eventEndDateTime": "2020-09-18 22:00:00.000", '
        '"eventLocation": "הנשיא 6, פתח-תקווה", '
        '"eventManager": "shr.harari@gmail.com" '
      '}'
      ']';

    return eventsListJson;
  }
  //#endregion

  //#region Create Json Rows: Messages [Data for Debug]
  static String createJsonRowsForMessages() {
        final String longMessageText = "שלום לכולם, הודעה ארוכה\\nעם כמה שורות\\nשורה שלישית\\nועוד שורה ארוכה עם הרבה מילים שצריכות להיות בכמה שורות";
        final String extraLongMessageText = "הודעה חשובה וארוכה\\nעם כמה שורות\\nשורה שלישית\\nועוד שורה ארוכה עם הרבה מילים שצריכות להיות בכמה שורות\\n"
            "עוד טקסט -- ועוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --\\n"
            "עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --\\n"
            "עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --"
            "עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --עוד טקסט --\\n"
            "שורה חדשה עם טקסט נוסף שאמור לקפוץ שורה לאחר 40 תווים \\n --- עוד טקסט --   עוד טקסט --\\n עוד שורה - שורה אחרונה ";

    String messagesListJson =
      '['
      '{'
        '"messageId": "1", '
        '"composerId": "1", '
        '"messageText": "שלום רב, הודעה ראשונה", '
        '"messageCreatedDateTime": "2019-04-29 09:40:00.000" '
      '},'
      '{'
        '"messageId": "2", '
        '"composerId": "1", '
        '"messageText": "שלום רב, הודעה שנייה", '
        '"messageCreatedDateTime": "2020-04-15 11:30:00.000" '
      '},'
      '{'
        '"messageId": "3", '
        '"composerId": "1", '
        '"messageText": "$longMessageText", '
        '"messageCreatedDateTime": "2020-05-22 17:13:00.000" '
      '},'
      '{'
        '"messageId": "4", '
        '"composerId": "1", '
        '"messageText": "$extraLongMessageText", '
        '"messageCreatedDateTime": "2020-08-18 08:50:00.000" '
      '}'
      ']';

    return messagesListJson;
  }
  //#endregion

  //#region Create Json Rows: Rotary Role [Data for Debug]
  static String createJsonRowsForRotaryRole() {

    String rolesListJson =
        '['
        '{'
        '"roleId": 1, '
        '"roleEnum": 1, '
        '"roleName": "יושב ראש" '
        '},'
        '{'
        '"roleId": 2, '
        '"roleEnum": 2, '
        '"roleName": "גזבר" '
        '},'
        '{'
        '"roleId": 3, '
        '"roleEnum": 3, '
        '"roleName": "מזכיר אזור" '
        '},'
        '{'
        '"roleId": 4, '
        '"roleEnum": 4, '
        '"roleName": "מזכיר אשכול" '
        '},'
        '{'
        '"roleId": 5, '
        '"roleEnum": 5, '
        '"roleName": "מזכיר מועדון" '
        '},'
        '{'
        '"roleId": 6, '
        '"roleEnum": 6, '
        '"roleName": "חבר" '
        '}'
        ']';

    return rolesListJson;
  }
  //#endregion

  //#region Create Json Rows: Rotary Area [Data for Debug]
  static String createJsonRowsForRotaryArea() {

    String rotaryAreasListJson =
      '['
        '{'
          '"areaId": 1, '
          '"areaName": "ישראל" '
        '},'
        '{'
          '"areaId": 2, '
          '"areaName": "ארצות הברית" '
        '},'
        '{'
          '"areaId": 3, '
          '"areaName": "צרפת" '
        '}'
      ']';

    return rotaryAreasListJson;
  }
  //#endregion

  //#region Create Json Rows: Rotary Cluster [Data for Debug]
  static String createJsonRowsForRotaryCluster(String aAreaName) {
    String rotaryClusterListJson;

    switch (aAreaName) {
      case 'ישראל':         // ישראל
        rotaryClusterListJson =
          '['
            '{'
              '"clusterId": 1, '
              '"clusterName": "גוש דן" '
            '},'
            '{'
              '"clusterId": 2, '
              '"clusterName": "שומרון" '
            '},'
            '{'
              '"clusterId": 3, '
              '"clusterName": "חיפה והקריות" '
            '}'
          ']';
        break;
      case 'ארצות הברית':         // ארצות הברית
        rotaryClusterListJson =
        '['
          '{'
            '"clusterId": 1, '
            '"clusterName": "חוף מזרחי" '
          '},'
          '{'
            '"clusterId": 2, '
            '"clusterName": "חוף מערבי" '
          '}'
        ']';
        break;
      case 'צרפת':         // צרפת
        rotaryClusterListJson =
        '['
          '{'
            '"clusterId": 1, '
            '"clusterName": "מרכז צרפת" '
          '},'
          '{'
            '"clusterId": 2, '
            '"clusterName": "אזור החוף" '
          '}'
        ']';
        break;
    }
    return rotaryClusterListJson;
  }
  //#endregion

  //#region Create Json Rows: Rotary Cluster OLD [Data for Debug]
  static String createJsonRowsForRotaryClusterOLD() {

    String rotaryClusterListJson =
        '['
        '{'
        '"areaId": 1, '
        '"clusterId": 1, '
        '"clusterName": "מרכז" '
        '},'
        '{'
        '"areaId": 1, '
        '"clusterId": 2, '
        '"clusterName": "שומרון" '
        '},'
        '{'
        '"areaId": 1, '
        '"clusterId": 3, '
        '"clusterName": "צפון" '
        '},'
        '{'
        '"areaId": 2, '
        '"clusterId": 1, '
        '"clusterName": "מזרח" '
        '},'
        '{'
        '"areaId": 2, '
        '"clusterId": 2, '
        '"clusterName": "מערב" '
        '},'
        '{'
        '"areaId": 3, '
        '"clusterId": 1, '
        '"clusterName": "מרכז" '
        '},'
        '{'
        '"areaId": 3, '
        '"clusterId": 2, '
        '"clusterName": "החוף" '
        '}'
        ']';

    return rotaryClusterListJson;
  }
  //#endregion

  //#region Create Json Rows: Rotary Club [Data for Debug]
  static String createJsonRowsForRotaryClub(String  aClusterName) {
    String rotaryClubsListJson;

    switch (aClusterName) {
      case 'גוש דן':
        rotaryClubsListJson =
        '['
          '{'
            '"clubId": 1, '
            '"clubName": "תל-אביב", '
            '"clubAddress": "תל-אביב, ויצמן 1", '
            '"clubMail": "tel-aviv@rotary.net", '
            '"clubManagerId": "1" '
          '},'
          '{'
            '"clubId": 2, '
            '"clubName": "כפר-סבא", '
            '"clubAddress": "כפר-סבא, ויצמן 1", '
            '"clubMail": "kfar-saba@rotary.net", '
            '"clubManagerId": "1" '
          '}'
        ']';
        break;
      case 'שומרון':
        rotaryClubsListJson =
        '['
          '{'
            '"clubId": 1, '
            '"clubName": "קיסריה", '
            '"clubAddress": "קיסריה, ויצמן 1", '
            '"clubMail": "caesarea@rotary.net", '
            '"clubManagerId": "2" '
          '},'
          '{'
            '"clubId": 2, '
            '"clubName": "חדרה", '
            '"clubAddress": "חדרה, ויצמן 1", '
            '"clubMail": "hadera@rotary.net", '
            '"clubManagerId": "2" '
          '},'
          '{'
            '"clubId": 3, '
            '"clubName": "כפר יונה", '
            '"clubAddress": "כפר יונה, ויצמן 1", '
            '"clubMail": "kfar-yona@rotary.net", '
            '"clubManagerId": "2" '
          '},'
          '{'
            '"clubId": 4, '
            '"clubName": "פרדס חנה", '
            '"clubAddress": "פרדס חנה, ויצמן 1", '
            '"clubMail": "pardes-hana@rotary.net", '
            '"clubManagerId": "3" '
          '}'
        ']';
        break;
      case 'חיפה והקריות':
        rotaryClubsListJson =
        '['
          '{'
            '"clubId": 1, '
            '"clubName": "חיפה", '
            '"clubAddress": "חיפה, ויצמן 1", '
            '"clubMail": "haiffa@rotary.net", '
            '"clubManagerId": "3" '
          '},'
          '{'
            '"clubId": 2, '
            '"clubName": "נהריה", '
            '"clubAddress": "נהריה, ויצמן 1", '
            '"clubMail": "naharia@rotary.net", '
            '"clubManagerId": "4" '
          '}'
        ']';
        break;
      case 'חוף מזרחי':
        rotaryClubsListJson =
        '['
          '{'
            '"clubId": 1, '
            '"clubName": "ניו-יורק", '
            '"clubAddress": "ניו-יורק, השדרה החמישית 99", '
            '"clubMail": "naharia@rotary.net", '
            '"clubManagerId": "4" '
          '}'
        ']';
        break;
      case 'חוף מערבי':
        break;
      case 'מרכז צרפת':
        rotaryClubsListJson =
        '['
          '{'
            '"clubId": 1, '
            '"clubName": "פריז", '
            '"clubAddress": "פריז, שאנז-אליזה 1", '
            '"clubMail": "naharia@rotary.net", '
            '"clubManagerId": "4" '
          '}'
        ']';
        break;
      case 'אזור החוף':
        break;
    }
    return rotaryClubsListJson;
  }
  //#endregion

  //#region Create Json Rows: Rotary Club OLD [Data for Debug]
  static String createJsonRowsForRotaryClubOLD() {

    String rotaryClubsListJson =
        '['
        '{'
        '"areaId": 1, '
        '"clusterId": 1, '
        '"clubId": 1, '
        '"clubName": "תל-אביב", '
        '"clubAddress": "תל-אביב, ויצמן 1", '
        '"clubMail": "tel-aviv@rotary.net", '
        '"clubManagerId": "1" '
        '},'
        '{'
        '"areaId": 1, '
        '"clusterId": 1, '
        '"clubId": 2, '
        '"clubName": "כפר-סבא", '
        '"clubAddress": "כפר-סבא, ויצמן 1", '
        '"clubMail": "kfar-saba@rotary.net", '
        '"clubManagerId": "1" '
        '},'
        '{'
        '"areaId": 1, '
        '"clusterId": 2, '
        '"clubId": 1, '
        '"clubName": "קיסריה", '
        '"clubAddress": "קיסריה, ויצמן 1", '
        '"clubMail": "caesarea@rotary.net", '
        '"clubManagerId": "2" '
        '},'
        '{'
        '"areaId": 1, '
        '"clusterId": 2, '
        '"clubId": 2, '
        '"clubName": "חדרה", '
        '"clubAddress": "חדרה, ויצמן 1", '
        '"clubMail": "hadera@rotary.net", '
        '"clubManagerId": "2" '
        '},'
        '{'
        '"areaId": 1, '
        '"clusterId": 2, '
        '"clubId": 3, '
        '"clubName": "כפר יונה", '
        '"clubAddress": "כפר יונה, ויצמן 1", '
        '"clubMail": "kfar-yona@rotary.net", '
        '"clubManagerId": "2" '
        '},'
        '{'
        '"areaId": 1, '
        '"clusterId": 2, '
        '"clubId": 4, '
        '"clubName": "פרדס חנה", '
        '"clubAddress": "פרדס חנה, ויצמן 1", '
        '"clubMail": "pardes-hana@rotary.net", '
        '"clubManagerId": "3" '
        '},'
        '{'
        '"areaId": 1, '
        '"clusterId": 3, '
        '"clubId": 1, '
        '"clubName": "חיפה", '
        '"clubAddress": "חיפה, ויצמן 1", '
        '"clubMail": "haiffa@rotary.net", '
        '"clubManagerId": "3" '
        '},'
        '{'
        '"areaId": 1, '
        '"clusterId": 3, '
        '"clubId": 2, '
        '"clubName": "נהריה", '
        '"clubAddress": "נהריה, ויצמן 1", '
        '"clubMail": "naharia@rotary.net", '
        '"clubManagerId": "4" '
        '},'
        '{'
        '"areaId": 2, '
        '"clusterId": 1, '
        '"clubId": 1, '
        '"clubName": "ניו-יורק", '
        '"clubAddress": "ניו-יורק, השדרה החמישית 99", '
        '"clubMail": "naharia@rotary.net", '
        '"clubManagerId": "4" '
        '},'
        '{'
        '"areaId": 3, '
        '"clusterId": 1, '
        '"clubId": 1, '
        '"clubName": "פריז", '
        '"clubAddress": "פריז, שאנז-אליזה 1", '
        '"clubMail": "naharia@rotary.net", '
        '"clubManagerId": "4" '
        '}'
        ']';

    return rotaryClubsListJson;
  }
  //#endregion
}