
class InitDataBaseData {

  //#region Create Json Rows PersonCard [Data for Debug]
  static String createJsonRowsForPersonCards() {
    final String someText = "\\nשל כרטיס הביקור של אלק באלדווי\\nפירוט נוסף\\nועוד פירוט\\nשורה נונספת ארוכה מאודדדדדדדדדדד דדדדדדדדדדדדד דדדדדדדדדדדד  דדדדד\\nועוד שורה ארררררוככככה יחדגיכחגי דגיכגדי דגכי ידגכי דגכי דגכי דגכי\\nסוף";

    String personCardRowsJson =
        '['
        '{'
        '"emailId": "shr.harari@gmail.com", '
        '"email": "shr.harari@gmail.com", '
        '"firstName": "שחר", '
        '"lastName": "הררי", '
        '"firstNameEng": "Shahar", '
        '"lastNameEng": "Harari", '
        '"phoneNumber": "+972525464640", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "525464640", '
        '"phoneNumberCleanLongFormat": "972525464640", '
        '"pictureUrl": "shr.harari@gmail.com.jpg", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של שחר הררי", '
        '"internetSiteUrl": "https://www.google.co.il/", '
        '"address": "הנשיאים 6, הוד-השרון ישראל" '
        '},'
        '{'
        '"emailId": "alec.baldwin@gmail.com", '
        '"email": "alec.baldwin@gmail.com", '
        '"firstName": "אלק", '
        '"lastName": "באלדווי", '
        '"firstNameEng": "Alec", '
        '"lastNameEng": "Baldwin", '
        '"phoneNumber": "+972521111111", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "521111111", '
        '"phoneNumberCleanLongFormat": "972521111111", '
        '"pictureUrl": "alec_baldwin@gmail.com.jpg", '
        '"cardDescription": "$someText", '
        '"internetSiteUrl": "", '
        '"address": "ויצמן 32, כפר-סבא ישראל" '
        '},'
        '{'
        '"emailId": "gal_gadot@gmail.com", '
        '"email": "gal_gadot@gmail.com", '
        '"firstName": "גל", '
        '"lastName": "גדות", '
        '"firstNameEng": "Gal", '
        '"lastNameEng": "Gadot", '
        '"phoneNumber": "+972522222222", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "522222222", '
        '"phoneNumberCleanLongFormat": "972522222222", '
        '"pictureUrl": "gal_gadot@gmail.com.jpg", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של גל גדות", '
        '"internetSiteUrl": "", '
        '"address": "יפו 32 ירושלים ישראל" '
        '},'
        '{'
        '"emailId": "tom_cruise@gmail.com", '
        '"email": "tom_cruise@gmail.com", '
        '"firstName": "טום", '
        '"lastName": "קרוז", '
        '"firstNameEng": "Tom", '
        '"lastNameEng": "Cruise", '
        '"phoneNumber": "+972523333333", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "523333333", '
        '"phoneNumberCleanLongFormat": "972523333333", '
        '"pictureUrl": "tom_cruise@gmail.com.jpg", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של טום קרוז", '
        '"internetSiteUrl": "", '
        '"address": "הכנסת 1, ירושלים" '
        '},'
        '{'
        '"emailId": "cameron_diaz@gmail.com", '
        '"email": "cameron_diaz@gmail.com", '
        '"firstName": "קמרון", '
        '"lastName": "דיאז", '
        '"firstNameEng": "Cameron", '
        '"lastNameEng": "Diaz", '
        '"phoneNumber": "+972524444444", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "524444444", '
        '"phoneNumberCleanLongFormat": "972524444444", '
        '"pictureUrl": "cameron_diaz@gmail.com.jpg", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של קמרון דיאז", '
        '"internetSiteUrl": "", '
        '"address": "תל-חי 18, כפר-סבא ישראל" '
        '},'
        '{'
        '"emailId": "harrison_ford@gmail.com", '
        '"email": "harrison_ford@gmail.com", '
        '"firstName": "האריסון", '
        '"lastName": "פורד", '
        '"firstNameEng": "Harrison", '
        '"lastNameEng": "Ford", '
        '"phoneNumber": "+972525555555", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "525555555", '
        '"phoneNumberCleanLongFormat": "972525555555", '
        '"pictureUrl": "harrison_ford@gmail.com.jpg", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של האריסון פורד", '
        '"internetSiteUrl": "", '
        '"address": "סוקולוב 6, נתניה" '
        '},'
        '{'
        '"emailId": "jack_nicholson@gmail.com", '
        '"email": "jack_nicholson@gmail.com", '
        '"firstName": "גק", '
        '"lastName": "ניקולסון", '
        '"firstNameEng": "Jack", '
        '"lastNameEng": "Nicholson", '
        '"phoneNumber": "+972526666666", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "526666666", '
        '"phoneNumberCleanLongFormat": "9726666666", '
        '"pictureUrl": "jack_nicholson@gmail.com.jpg", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של גק ניקולסון", '
        '"internetSiteUrl": "", '
        '"address": "ויצמן 6, חדרה" '
        '},'
        '{'
        '"emailId": "julia_roberts@gmail.com", '
        '"email": "julia_roberts@gmail.com", '
        '"firstName": "גוליה", '
        '"lastName": "רוברטס", '
        '"firstNameEng": "Julia", '
        '"lastNameEng": "Roberts", '
        '"phoneNumber": "+972527777777", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "527777777", '
        '"phoneNumberCleanLongFormat": "97257777777", '
        '"pictureUrl": "julia_roberts@gmail.com.jpg", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של גוליה רוברטס", '
        '"internetSiteUrl": "google.com", '
        '"address": "סוקולוב 6, רמת-השרון" '
        '},'
        '{'
        '"emailId": "paul_newman@gmail.com", '
        '"email": "paul_newman@gmail.com", '
        '"firstName": "פול", '
        '"lastName": "ניומן", '
        '"firstNameEng": "Paul", '
        '"lastNameEng": "Newman", '
        '"phoneNumber": "+972528888888", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "528888888", '
        '"phoneNumberCleanLongFormat": "97258888888", '
        '"pictureUrl": "paul_newman@gmail.com.jpg", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של פול ניומן", '
        '"internetSiteUrl": "google.com", '
        '"address": "וינגייט 56, באר-שבע" '
        '},'
        '{'
        '"emailId": "robert_de_niro@gmail.com", '
        '"email": "robert_de_niro@gmail.com", '
        '"firstName": "רוברט", '
        '"lastName": "דה-נירו", '
        '"firstNameEng": "Robert", '
        '"lastNameEng": "De_niro", '
        '"phoneNumber": "+972529999999", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "529999999", '
        '"phoneNumberCleanLongFormat": "97259999999", '
        '"pictureUrl": "robert_de_niro@gmail.com.jpg", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של רוברט דה-נירו", '
        '"internetSiteUrl": "google.com", '
        '"address": "הנשיא 6, פתח-תקווה" '
        '},'
        '{'
        '"emailId": "uma_thurman@gmail.com", '
        '"email": "uma_thurman@gmail.com", '
        '"firstName": "אומה", '
        '"lastName": "תורמן", '
        '"firstNameEng": "Uma", '
        '"lastNameEng": "Thurman", '
        '"phoneNumber": "+972529999999", '
        '"phoneNumberDialCode": "972", '
        '"phoneNumberParse": "529999999", '
        '"phoneNumberCleanLongFormat": "97259999999", '
        '"pictureUrl": "uma_thurman@gmail.com.jpg", '
        '"cardDescription": "תיאור מפורט של כרטיס הביקור של אומה תורמן", '
        '"internetSiteUrl": "google.com", '
        '"address": "6767 Hollywood Blvd, Los Angeles, CA 90028, ארצות הברית" '
        '}'
        ']';

    return personCardRowsJson;
  }
//#endregion

  //#region Create Json Rows Users [Data for Debug]
  static String createJsonRowsForUsers() {

    String userRowsJson =
        '['
        '{'
        '"emailId": "shr.harari@gmail.com", '
        '"firstName": "שחר", '
        '"lastName": "הררי", '
        '"password": "qqqq", '
        '"userType": "SystemAdmin", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"emailId": "alec.baldwin@gmail.com", '
        '"firstName": "אלק", '
        '"lastName": "באלדווין", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"emailId": "gal_gadot@gmail.com", '
        '"firstName": "גל", '
        '"lastName": "גדות", '
        '"password": "qqqq", '
        '"userType": "SystemAdmin", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"emailId": "tom_cruise@gmail.com", '
        '"email": "tom_cruise@gmail.com", '
        '"firstName": "טום", '
        '"lastName": "קרוז", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"emailId": "cameron_diaz@gmail.com", '
        '"firstName": "קמרון", '
        '"lastName": "דיאז", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"emailId": "harrison_ford@gmail.com", '
        '"firstName": "האריסון", '
        '"lastName": "פורד", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"emailId": "jack_nicholson@gmail.com", '
        '"firstName": "גק", '
        '"lastName": "ניקולסון", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"emailId": "julia_roberts@gmail.com", '
        '"firstName": "גוליה", '
        '"lastName": "רוברטס", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"emailId": "paul_newman@gmail.com", '
        '"firstName": "פול", '
        '"lastName": "ניומן", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"emailId": "robert_de_niro@gmail.com", '
        '"firstName": "רוברט", '
        '"lastName": "דה-נירו", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"emailId": "uma_thurman@gmail.com", '
        '"firstName": "אומה", '
        '"lastName": "תורמן", '
        '"password": "qqqq", '
        '"userType": "RotaryMember", '
        '"stayConnected": 1 '
        '},'
        '{'
        '"emailId": "roie_shaposhnik@gmail.com", '
        '"firstName": "רועי", '
        '"lastName": "שפושניק", '
        '"password": "qqqq", '
        '"userType": "Guest", '
        '"stayConnected": 1 '
        '}'
        ']';

    return userRowsJson;
  }
//#endregion

}