name: rotary_net
description: Rotary Net Application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.5
  flutter_spinkit: ^4.1.2+1
  synchronized: ^2.2.0+1
  connectivity: ^0.4.8+6
  path_provider: ^1.6.14
  shared_preferences: ^0.5.7+3
  google_fonts: ^1.1.0
  http: ^0.12.1
  enum_to_string: ^1.0.9
  intl_phone_number_input: ^0.4.6+2
  url_launcher: ^5.5.0
  geolocator: ^5.3.2+2
  file_picker: ^1.13.3
  image_picker: ^0.6.7+7
  add_2_calendar: ^1.4.0
  sqflite: ^1.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/RotaryNetLogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/app_icon/
    - assets/images/person_cards/
    - assets/images/events/
    - assets/icons/
    - assets/background/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Heebo-Black
      fonts:
        - asset: fonts/Heebo/Heebo-Black.ttf
    - family: Heebo-Light
      fonts:
        - asset: fonts/Heebo/Heebo-Light.ttf
    - family: Rubik
      fonts:
        - asset: fonts/Rubik/Rubik-Black.ttf
        - asset: fonts/Rubik/Rubik-BlackItalic.ttf
        - asset: fonts/Rubik/Rubik-Bold.ttf
        - asset: fonts/Rubik/Rubik-BoldItalic.ttf
        - asset: fonts/Rubik/Rubik-Italic.ttf
        - asset: fonts/Rubik/Rubik-Light.ttf
        - asset: fonts/Rubik/Rubik-LightItalic.ttf
        - asset: fonts/Rubik/Rubik-Medium.ttf
        - asset: fonts/Rubik/Rubik-MediumItalic.ttf
        - asset: fonts/Rubik/Rubik-Regular.ttf

